"""table_categories

Revision ID: 473be5d62e68
Revises: ec85529b2ff5
Create Date: 2021-02-05 12:28:42.846559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473be5d62e68'
down_revision = 'ec85529b2ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    category_table = op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(category_table,
        [
            {'name': 'A day in the life'},
            {'name': 'A day to remember'},
            {'name': 'Vacation Day'},
            {'name': 'Special Day'},
        ]  
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
