"""table_colors

Revision ID: 3502d07a6dcc
Revises: 473be5d62e68
Create Date: 2021-02-05 12:30:18.329418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3502d07a6dcc'
down_revision = '473be5d62e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colors')
    # ### end Alembic commands ###
