"""user categories

Revision ID: e6e174f09340
Revises: ffdc0a98111c
Create Date: 2021-02-03 17:42:49.264411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e174f09340'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    category_table = op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(category_table,
        [
            {'name': 'A day in the life'},
            {'name': 'A day to remember'},
            {'name': 'Vaca Day'},
            {'name': 'Special Day'},
        ]  
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
