"""table_images

Revision ID: 10130432d812
Revises: db21b194e03a
Create Date: 2021-02-05 13:33:52.248400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10130432d812'
down_revision = 'db21b194e03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
